Hw02 express
alina-prosk/nodejs-homework-rest-api pull request #1
Opened 2022-12-29 19:12 UTC by alina-prosk

2022-12-29 19:17 UTC, KhYulian commented on routes/api/contacts.js
> +const contactsOperations = require("../../models/contacts");
Варто зробити деструктуризацію

2022-12-29 19:18 UTC, KhYulian commented on routes/api/contacts.js
> +    return result;
return res.status(404).json({
      message: `Product with id=${contactId} not found`,
    }); - для чого повертати в контроллері контакт?)

2022-12-29 19:19 UTC, KhYulian commented on models/contacts.js
> +    return res.status(500).json({ message: "Internal Error" });
для обробки помилок використовуйте next

2022-12-29 19:20 UTC, KhYulian commented on routes/api/contacts.js
> +      throw error;
Можете зробити свою кастомну помилку на основі Error, яка приматиме месседж та статус код

2022-12-29 19:20 UTC, KhYulian requested changes
ПОтрібне доопрацювання

2022-12-29 20:21 UTC, alina-prosk commented on routes/api/contacts.js
> +const contactsOperations = require("../../models/contacts");
зробила

2022-12-29 20:21 UTC, alina-prosk commented on routes/api/contacts.js
> +    return result;
Виправила

2022-12-29 20:21 UTC, alina-prosk commented on models/contacts.js
> +    return res.status(500).json({ message: "Internal Error" });
Я з тими всіма помилками трішки заплуталася. Потрібно замість 34 i 58  рядка вказати next(error)?

2022-12-29 20:21 UTC, alina-prosk commented on routes/api/contacts.js
> +      throw error;
Зробила

2022-12-29 22:49 UTC, KhYulian commented on models/contacts.js
> +    return res.status(500).json({ message: "Internal Error" });
в catch(error) {
  next(error)
}

2022-12-30 10:02 UTC, KhYulian commented on helpers/index.js
> +}
аося на увазі створити свій клас який буде наслідуватись від Error; class ErrorHttp extends Error {} - https://javascript.info/custom-errors
Поправити в 3 домашці

2022-12-30 10:03 UTC, KhYulian approved these changes
Чудова робота :heart::heart::heart:

2022-12-30 10:03 UTC, merged