add mongoose
alina-prosk/nodejs-homework-rest-api pull request #3
Opened 2023-01-19 09:11 UTC by alina-prosk

2023-01-19 14:38 UTC, KhYulian requested changes
Потрібні правки

2023-01-19 14:38 UTC, KhYulian commented on controllers/contacts/add.js
> +const add = async (req, res) => {
addContact / createContact

2023-01-19 14:38 UTC, KhYulian commented on controllers/contacts/add.js
> +    code: 201,
Непотрібні поля - видаляйте. res.status(201).json(result); (for example)

2023-01-19 14:38 UTC, KhYulian commented on model/contact.js
> +});
винесіть joiSchema, favoriteSchema в окремий файл

2023-01-19 14:38 UTC, KhYulian commented on server.js
> +main();
Можна використати IIFE

2023-01-19 14:48 UTC, alina-prosk commented on controllers/contacts/add.js
> +const add = async (req, res) => {
+

2023-01-19 15:29 UTC, alina-prosk reviewed
postman error 500

2023-01-19 15:29 UTC, alina-prosk commented on controllers/contacts/add.js
> +    code: 201,
+

2023-01-19 15:29 UTC, alina-prosk commented on model/contact.js
> +});
+ постмен тепер видає помилку  "message": "Cannot read properties of undefined (reading 'json')"

2023-01-19 15:29 UTC, alina-prosk commented on server.js
> +main();
+

2023-01-20 10:00 UTC, KhYulian commented on server.js
> +main();
Можна використати IIFE

2023-01-20 10:01 UTC, KhYulian commented on routes/api/contacts.js
> +const { contacts: ctrl } = require("../../controllers");
Зробіть деструктуризацію, щоб не писати кожного разу ctrl.

2023-01-20 10:01 UTC, KhYulian approved these changes
Чудова робота. Коменти візьміть до уваги при роботі над наступною

2023-01-20 10:01 UTC, merged